"""add_activation_columns

Revision ID: 585e21f183e6
Revises: 
Create Date: 2025-04-04 19:17:00.736370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585e21f183e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_activated', sa.Boolean(), nullable=True))
    op.add_column('Users', sa.Column('activation_token', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'Users', ['activation_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_column('Users', 'token_expires_at')
    op.drop_column('Users', 'activation_token')
    op.drop_column('Users', 'is_activated')
    # ### end Alembic commands ###
